# Generated by Django 4.0.8 on 2022-10-30 07:30

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_options_homepage_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_text',
            field=wagtail.fields.RichTextField(default='', help_text='short introduction to yourself or your company or etc'),
            preserve_default=False,
        ),
    ]
