# Generated by Django 4.0.8 on 2022-10-31 15:58

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_about_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='short introduction to yourself or your company or etc', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_subtitle',
            field=wagtail.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
