# Generated by Django 4.0.8 on 2022-11-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_services_alter_homepage_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='switch_diensten',
            field=models.BooleanField(default=True, verbose_name='Diensten aan/uit'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='switch_milestones',
            field=models.BooleanField(default=True, verbose_name='Mijlpalen aan/uit'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='switch_over',
            field=models.BooleanField(default=True, verbose_name='Over aan/uit'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='switch_portfolio',
            field=models.BooleanField(default=True, verbose_name='Portfolio aan/uit'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='switch_team',
            field=models.BooleanField(default=True, verbose_name='Team aan/uit'),
        ),
    ]
